sources:
  - name: walmart_databricks
    database: walmart # This is the same as your catalog name as you defined in Databricks
    schema: bronze # As defined in databricks
    tables:
      - name: orders
      - name: customers # this is the table_name
      - name: products
      - name: order_items
      - name: stores
      - name: employees
    